# VAULT CSI Driver installation information is located at
# https://github.com/hashicorp/vault-csi-provider
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.27.0
    releaseName: vault-csi-provider
    namespace: vault-csi-provider
    valuesInline:
      server:
        enabled: false
      injector:
        enabled: false
      csi:
        enabled: true
