apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-secret-store.yaml
  - route.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.27.0
    releaseName: vault-server
    namespace: vault-server
    valuesInline:
      global:
        openshift: true
      server:
        dev:
          enabled: true
        enabled: true
      injector:
        enabled: false
      csi:
        enabled: false
