apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml
- rbac.yaml

helmCharts:
- name: vault
  namespace: vault-server
  releaseName: vault-server
  repo: https://helm.releases.hashicorp.com
  valuesInline:
    csi:
      daemonSet:
        providersDir: /var/run/secrets-store-csi-providers
      enabled: true
    global:
      openshift: true
    injector:
      enabled: false
    server:
      dev:
        enabled: true
      enabled: true
  version: 0.27.0

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: vault-server-csi-provider
    path: daemonset-patch.yaml