apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - route.yaml
  - rbac.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.27.0
    releaseName: vault-server
    namespace: vault-server
    valuesInline:
      global:
        openshift: true
      server:
        image:
          repository: "registry.connect.redhat.com/hashicorp/vault"
          tag: "1.8.0-ubi"
        dev:
          enabled: true
        enabled: true
      injector:
        enabled: false
      csi:
        enabled: true
        daemonSet:
          providersDir: "/var/run/secrets-store-csi-providers"
