---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-server-internal.vault-server.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: "cm9vdA=="
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: prime-vault
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: vault-backend
      kind: SecretStore
  data:
  - key: test
    value: test-value
