apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-external
  namespace: <namespace>
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: managed-secretstore
    kind: SecretStore
  target:
    name: awssm-secret-access
    creationPolicy: Owner
  data:
  - secretKey: cummins #Name of the secret created in your OpenShift namespace
    remoteRef:
      key: dev/apps/kubecost #Name of the secret in AWS Secret Store
      property: cummins #Name of the key whose value you are trying to extract
