---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-controller
  namespace: argocd
spec:
  destination:
    namespace: team-control
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/poc-examples/managing-secrets'
    path: 'patterns/external-secrets/team-control'
    targetRevision: HEAD
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
