---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-csi-driver-provider
  namespace: openshift-gitops
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/poc-examples/managing-secrets'
    path: 'patterns/secrets-csi-driver/foundational/providers/vault'
    targetRevision: HEAD
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=false
