---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-server
  namespace: openshift-gitops
spec:
  destination:
    namespace: vault-server
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/poc-examples/managing-secrets'
    path: 'vault/config'
    targetRevision: HEAD
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=false
